<!DOCTYPE html>
<html lang="ja">
<?php
  include('html_header.php');
?>
<body>
<?php
  include('menu.php');
?>
<div style="padding-top:70px;background-color:#ccccff;">
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.

Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non quod perferendis quae accusantium vitae ipsum officiis eum voluptatum, ab ipsa, molestiae error tenetur dolor, officia, quidem esse inventore deleniti doloremque.
</div>
</body>
</html>
